### PR TITLE
SBT message fix duplicated query

### PR DESCRIPTION
**Pull request by xssnick**

### CODE REVIEW

**Review by Firontiu — APPROVED** [review]

**Comment by Hassan222-ux** [comment]
xssnick:main

**Review by Hassan222-ux — COMMENTED** [review]
fc

**Review by OniKyoko — APPROVED** [review]

**Review by care44cubs-max — COMMENTED** [review]
Yes

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho

**Review by care44cubs-max — COMMENTED** [review]
Yes

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho ☑️

**Review by albertoblue87-netizen — COMMENTED** [review]
Listo

**Review by albertoblue87-netizen — COMMENTED** [review]
Listo

**Comment by navedjuwale-creator** [comment]
Great, thanks. LGTM.

**Pull request merged**
